//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentCheckOut.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Location {
            get {
                return ((global::System.Drawing.Point)(this["Location"]));
            }
            set {
                this["Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size Size {
            get {
                return ((global::System.Drawing.Size)(this["Size"]));
            }
            set {
                this["Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Maximised {
            get {
                return ((bool)(this["Maximised"]));
            }
            set {
                this["Maximised"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MOVIE\\SQLEXPRESS;Initial Catalog=Camera;Persist Security Info=True;Us" +
            "er ID=CheckoutUser;Password=I32B2XFw")]
        public string CameraConnectionString {
            get {
                return ((string)(this["CameraConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point DocLocation {
            get {
                return ((global::System.Drawing.Point)(this["DocLocation"]));
            }
            set {
                this["DocLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size DocSize {
            get {
                return ((global::System.Drawing.Size)(this["DocSize"]));
            }
            set {
                this["DocSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DocMaximised {
            get {
                return ((bool)(this["DocMaximised"]));
            }
            set {
                this["DocMaximised"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("אין לך את ההרשאה הדרושה לפעולה זו")]
        public string MsgNoPermission {
            get {
                return ((string)(this["MsgNoPermission"]));
            }
            set {
                this["MsgNoPermission"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("לא ניתן להשלים פעולה")]
        public string MsgCantProceed {
            get {
                return ((string)(this["MsgCantProceed"]));
            }
            set {
                this["MsgCantProceed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("הצעת מחיר")]
        public string TITLE_QUOTE {
            get {
                return ((string)(this["TITLE_QUOTE"]));
            }
            set {
                this["TITLE_QUOTE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("תעודת השכרה")]
        public string TITLE_SHIPMENT {
            get {
                return ((string)(this["TITLE_SHIPMENT"]));
            }
            set {
                this["TITLE_SHIPMENT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("תעודת החזרה")]
        public string TITLE_RECEIVE {
            get {
                return ((string)(this["TITLE_RECEIVE"]));
            }
            set {
                this["TITLE_RECEIVE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("חשבון השכרה")]
        public string TITLE_BILL {
            get {
                return ((string)(this["TITLE_BILL"]));
            }
            set {
                this["TITLE_BILL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("מקור")]
        public string DOC_ORIGINAL {
            get {
                return ((string)(this["DOC_ORIGINAL"]));
            }
            set {
                this["DOC_ORIGINAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("העתק")]
        public string DOC_COPY {
            get {
                return ((string)(this["DOC_COPY"]));
            }
            set {
                this["DOC_COPY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("לא ניתן לשמור שדה זה ריק")]
        public string MsgCantSaveEmpty {
            get {
                return ((string)(this["MsgCantSaveEmpty"]));
            }
            set {
                this["MsgCantSaveEmpty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("חייב ערך מספרי")]
        public string MsgOnlyNumeric {
            get {
                return ((string)(this["MsgOnlyNumeric"]));
            }
            set {
                this["MsgOnlyNumeric"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.17")]
        public decimal VAT {
            get {
                return ((decimal)(this["VAT"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("בתוקף עד:")]
        public string DATE2_QUOTE {
            get {
                return ((string)(this["DATE2_QUOTE"]));
            }
            set {
                this["DATE2_QUOTE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("לחיוב מ:")]
        public string DATE2_SHIP {
            get {
                return ((string)(this["DATE2_SHIP"]));
            }
            set {
                this["DATE2_SHIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("לחיוב עד:")]
        public string DATE2_RECEIVE {
            get {
                return ((string)(this["DATE2_RECEIVE"]));
            }
            set {
                this["DATE2_RECEIVE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("האם לשמור שינויים?")]
        public string MsgSaveChanges {
            get {
                return ((string)(this["MsgSaveChanges"]));
            }
            set {
                this["MsgSaveChanges"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("לפני סגירה")]
        public string MsgBeforeClosing {
            get {
                return ((string)(this["MsgBeforeClosing"]));
            }
            set {
                this["MsgBeforeClosing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("טיוטה")]
        public string DOC_DRAFT {
            get {
                return ((string)(this["DOC_DRAFT"]));
            }
            set {
                this["DOC_DRAFT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("יש לשמור את המסמך לפני יצוא. האם לשמור?")]
        public string MsgNotSaved {
            get {
                return ((string)(this["MsgNotSaved"]));
            }
            set {
                this["MsgNotSaved"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("יש להשלים שדות נדרשים")]
        public string MsgMissingField {
            get {
                return ((string)(this["MsgMissingField"]));
            }
            set {
                this["MsgMissingField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4.6")]
        public float CurrentVersion {
            get {
                return ((float)(this["CurrentVersion"]));
            }
            set {
                this["CurrentVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("גרסת תוכנה זו אינה האחרונה, נא להשתמש בגרסא")]
        public string MsgBadVersion {
            get {
                return ((string)(this["MsgBadVersion"]));
            }
            set {
                this["MsgBadVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("יש לבחור פרוייקט קודם")]
        public string MsgNoProject {
            get {
                return ((string)(this["MsgNoProject"]));
            }
            set {
                this["MsgNoProject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("פריטים במסמך הוסרו מפני שכבר זוכו")]
        public string MsgItemsReturned {
            get {
                return ((string)(this["MsgItemsReturned"]));
            }
            set {
                this["MsgItemsReturned"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("הודעה")]
        public string MsgMessage {
            get {
                return ((string)(this["MsgMessage"]));
            }
            set {
                this["MsgMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("כמות הפריטים במסמך זה השתנו מפני שחלקם כבר זוכו")]
        public string MsgItemsQttyChange {
            get {
                return ((string)(this["MsgItemsQttyChange"]));
            }
            set {
                this["MsgItemsQttyChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("טעות")]
        public string MsgError {
            get {
                return ((string)(this["MsgError"]));
            }
            set {
                this["MsgError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("חייב ערך גבוה מ-0")]
        public string MsgValueHigherThanZero {
            get {
                return ((string)(this["MsgValueHigherThanZero"]));
            }
            set {
                this["MsgValueHigherThanZero"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("חייב ערך מספרי שלם")]
        public string MsgMustBeNum {
            get {
                return ((string)(this["MsgMustBeNum"]));
            }
            set {
                this["MsgMustBeNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("יש לבחור פריט קיים מהקטלוג")]
        public string MsgNoItem {
            get {
                return ((string)(this["MsgNoItem"]));
            }
            set {
                this["MsgNoItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("הגעת לסוף המסמך")]
        public string MsgEndOfDoc {
            get {
                return ((string)(this["MsgEndOfDoc"]));
            }
            set {
                this["MsgEndOfDoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("מציאת פריט")]
        public string MsgFindInDoc {
            get {
                return ((string)(this["MsgFindInDoc"]));
            }
            set {
                this["MsgFindInDoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(none)")]
        public string PathLetterHead {
            get {
                return ((string)(this["PathLetterHead"]));
            }
            set {
                this["PathLetterHead"] = value;
            }
        }
    }
}
